{{ if .Values.security.networkpolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "app.fullname" $ }}-deny-from-other-namespaces
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" $ }}
    release: {{ $.Release.Name }}
    chart: {{ template "app.chart" $ }}
    heritage: {{ $.Release.Service }}
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "app.fullname" $ }}-allow-external-to-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" $ }}
    release: {{ $.Release.Name }}
    chart: {{ template "app.chart" $ }}
    heritage: {{ $.Release.Service }}
spec:
  podSelector:
    matchLabels:
      component: frontend
      app: {{ template "app.name" $ }}
      release: {{ $.Release.Name }}
  ingress:
  - from: []
{{- if .Values.zipkin.enabled -}}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "app.fullname" $ }}-allow-external-to-zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" $ }}
    release: {{ $.Release.Name }}
    chart: {{ template "app.chart" $ }}
    heritage: {{ $.Release.Service }}
spec:
  podSelector:
    matchLabels:
      component: zipkin
      app: {{ template "app.name" $ }}
  ingress:
  - from: []
---
{{ end }}
{{ end }}