{{- if .Values.zipkin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" $ }}-zipkin
  labels:
    component: zipkin
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  selector:
    component: zipkin
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
  ports:
  - port: 9411
    targetPort: 9411
{{- end }}